import React, { useState, useEffect } from "react"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Checkbox } from "@/components/ui/checkbox"
import { FileText, Eye, Loader2, Sparkles } from "lucide-react"
import axios from 'axios'
import API_URL from '@/config/api'
// Remove the useSession import since we're getting sessionId as a prop

interface CSVUploadDialogProps {
  isOpen: boolean
  onClose: () => void
  fileName: string
  filePreview?: {
    headers: string[]
    rows: any[][]
    name: string
    description: string
  }
  onConfirm: (name: string, description: string, fillNulls: boolean, convertTypes: boolean) => void
  isSubmitting: boolean
  existingData?: any
  sessionId: string // Add sessionId prop
}

export default function CSVUploadDialog({
  isOpen,
  onClose,
  fileName,
  filePreview,
  onConfirm,
  isSubmitting,
  existingData,
  sessionId
}: CSVUploadDialogProps) {
  const [datasetName, setDatasetName] = useState('')
  const [description, setDescription] = useState('')
  const [activeTab, setActiveTab] = useState<"edit" | "preview">("edit")
  const [isGeneratingDescription, setIsGeneratingDescription] = useState(false)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false) // Track if auto-generation has been done
  const [generatedDescriptions, setGeneratedDescriptions] = useState<Map<string, string>>(new Map()) // Cache for generated descriptions
  
  // ADD THESE NEW STATE VARIABLES
  const [fillNulls, setFillNulls] = useState(true)
  const [convertTypes, setConvertTypes] = useState(true)

  // Auto-trigger description generation on EVERY upload
  useEffect(() => {
    if (isOpen && filePreview && !hasAutoGenerated) {
      // Set the dataset name from preview
      const newDatasetName = filePreview.name || fileName.replace(/\.csv$/i, '')
      setDatasetName(newDatasetName)
      
      // Create cache key based on file content
      const datasetKey = `${fileName}_${filePreview.headers.join('_')}_${filePreview.rows.length}`
      
      // Check if this is the default dataset
      if (filePreview.name === "Housing Dataset") {
        // Default dataset: use backend description as-is
        console.log('📋 Default dataset - using backend description')
        setDescription(filePreview.description)
        setHasAutoGenerated(true)
      } else {
        // Check if we have a cached description for this file
        const cachedDescriptions = getCachedDescriptions()
        const cachedDesc = cachedDescriptions.get(datasetKey)
        
        if (cachedDesc) {
          // Previously uploaded file: load cached description
          console.log('📋 Loading cached description for:', newDatasetName)
          setDescription(cachedDesc)
          setHasAutoGenerated(true)
        } else {
          // New file: auto-generate description
          console.log('🔍 New file - auto-generating description')
          setDescription(filePreview.description || `CSV data from ${fileName}`)
          
          const timer = setTimeout(() => {
            handleAutoGenerate(newDatasetName, datasetKey)
            setHasAutoGenerated(true)
          }, 100)
          
          return () => clearTimeout(timer)
        }
      }
    }
  }, [isOpen, filePreview, hasAutoGenerated])

  // Reset form when dialog closes
  useEffect(() => {
    if (!isOpen) {
      setDatasetName('')
      setDescription('')
      setActiveTab("edit")
      setIsGeneratingDescription(false)
      setHasAutoGenerated(false) // Reset auto-generation flag
    }
  }, [isOpen])

  const handleClose = () => {
    if (!isSubmitting) {
      setDatasetName('')
      setDescription('')
      setActiveTab("edit")
      onClose()
    }
  }

  const handleSubmit = () => {
    if (!datasetName.trim() || !description.trim()) return
    onConfirm(datasetName.trim(), description.trim(), fillNulls, convertTypes)
  }

  const handleAutoGenerate = async (explicitDatasetName?: string, cacheKey?: string) => {
    if (!sessionId || !filePreview) {
      console.error('No session ID or file preview available for description generation')
      return
    }
    
    // Don't auto-generate for default dataset
    if (filePreview.name === "Housing Dataset") {
      console.log('📋 Default dataset - not auto-generating')
      return
    }
    
    const currentDatasetName = explicitDatasetName || datasetName
    
    setIsGeneratingDescription(true)
    
    try {
      console.log('🔍 Auto-generating description for dataset:', currentDatasetName)
      
      const response = await axios.post(`${API_URL}/generate-description-from-preview`, {
        headers: filePreview.headers,
        rows: filePreview.rows,
        name: currentDatasetName,
        existingDescription: description
      }, {
        headers: {
          'Content-Type': 'application/json',
          ...(sessionId && { 'X-Session-ID': sessionId }),
        }
      })
      
      if (response.data && response.data.description) {
        const generatedDesc = response.data.description
        setDescription(generatedDesc)
        
        // Save to cache
        if (cacheKey) {
          saveCachedDescription(cacheKey, generatedDesc)
        }
        
        console.log('✅ Description generated and cached')
      } else {
        console.error('No description received from backend')
      }
    } catch (error) {
      console.error('Error generating description:', error)
      setDescription('Failed to generate description. Please try again or enter manually.')
    } finally {
      setIsGeneratingDescription(false)
    }
  }

  // Separate function for button click (no parameters)
  const handleAutoGenerateClick = () => {
    const datasetKey = `${fileName}_${filePreview?.headers.join('_')}_${filePreview?.rows.length}`
    handleAutoGenerate(undefined, datasetKey)
  }

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-5xl max-h-[90vh] flex flex-col">
        <DialogHeader className="flex-shrink-0">
          <DialogTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-[#FF7F7F]" />
            Dataset Details
          </DialogTitle>
        </DialogHeader>

        <div className="flex-1 min-h-0 flex flex-col space-y-4 overflow-hidden">
          {/* Dataset Name - Fixed height */}
          <div className="flex-shrink-0 space-y-2">
            <label htmlFor="datasetName" className="text-sm font-medium">
              Dataset Name
            </label>
            <Input
              id="datasetName"
              placeholder="Enter dataset name..."
              value={datasetName}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setDatasetName(e.target.value)}
              disabled={isSubmitting}
              className="focus:ring-[#FF7F7F] focus:border-[#FF7F7F]"
            />
          </div>

          {/* Description - Fixed height */}
          <div className="flex-shrink-0 space-y-3">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium">Description</label>
              <Button
                variant="outline"
                size="sm"
                onClick={handleAutoGenerateClick} // Use the new function
                disabled={isSubmitting || !filePreview || isGeneratingDescription}
                className="text-xs hover:bg-[#FF7F7F]/10 hover:border-[#FF7F7F]/30 flex items-center gap-1"
              >
                {isGeneratingDescription ? (
                  <Loader2 className="w-3 h-3 animate-spin" />
                ) : (
                  <Sparkles className="w-3 h-3" />
                )}
                Auto-generate
              </Button>
            </div>

            <Tabs value={activeTab} onValueChange={(value: string) => setActiveTab(value as "edit" | "preview")} className="w-full">
              <TabsList className="grid w-full grid-cols-2 h-8">
                <TabsTrigger value="edit" className="text-xs">Edit</TabsTrigger>
                <TabsTrigger value="preview" className="text-xs">Preview</TabsTrigger>
              </TabsList>
              
              <TabsContent value="edit" className="mt-3">
                <Textarea
                  placeholder="Describe what this dataset contains and its purpose..."
                  value={description}
                  onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setDescription(e.target.value)}
                  disabled={isSubmitting}
                  className="min-h-[120px] focus:ring-[#FF7F7F] focus:border-[#FF7F7F]"
                />
              </TabsContent>
              
              <TabsContent value="preview" className="mt-3">
                <div className="min-h-[120px] p-3 bg-gray-50 rounded-md border">
                  <div className="text-sm text-gray-700 whitespace-pre-wrap">
                    {description || "No description provided"}
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          </div>

          {/* Preprocessing Options - Updated to match Excel dialog styling */}
          <div className="flex-shrink-0 space-y-3">
            <label className="text-sm font-medium">Preprocessing Options</label>
            
            <div className="flex items-center space-x-2">
              <Checkbox
                id="fillNulls"
                checked={fillNulls}
                onCheckedChange={(checked) => setFillNulls(checked as boolean)}
              />
              <label
                htmlFor="fillNulls"
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer"
              >
                Fill nulls
              </label>
            </div>
            
            <div className="flex items-center space-x-2">
              <Checkbox
                id="convertTypes"
                checked={convertTypes}
                onCheckedChange={(checked) => setConvertTypes(checked as boolean)}
              />
              <label
                htmlFor="convertTypes"
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer"
              >
                Convert types for better analysis
              </label>
            </div>
          </div>

          {/* Data Preview - Flexible height with internal scrolling */}
          {filePreview && (
            <div className="flex-1 min-h-0 flex flex-col space-y-3">
              <label className="text-sm font-medium flex-shrink-0">Data Preview</label>
              <div className="flex-1 min-h-0 border rounded-md overflow-hidden flex flex-col">
                <div className="bg-gray-50 px-3 py-2 text-xs font-medium text-gray-600 border-b flex-shrink-0">
                  {filePreview.headers.length} columns, {filePreview.rows.length} sample rows
                </div>
                <div className="flex-1 min-h-0 overflow-auto">
                  <table className="w-full text-xs min-w-max">
                    <thead className="sticky top-0 bg-gray-100">
                      <tr>
                        {filePreview.headers.map((header: string, index: number) => (
                          <th key={index} className="px-2 py-1 text-left font-medium text-gray-700 border-r whitespace-nowrap">
                            {header}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {filePreview.rows.map((row: any[], rowIndex: number) => (
                        <tr key={rowIndex} className="border-b hover:bg-gray-50">
                          {row.map((cell: any, cellIndex: number) => (
                            <td key={cellIndex} className="px-2 py-1 border-r text-gray-600 whitespace-nowrap">
                              {cell !== null && cell !== undefined ? String(cell) : ''}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          )}

          {/* Action Buttons - Fixed at bottom */}
          <div className="flex-shrink-0 flex justify-end gap-3 pt-4 border-t">
            <Button
              variant="outline"
              onClick={handleClose}
              disabled={isSubmitting}
            >
              Cancel
            </Button>
            <Button
              onClick={handleSubmit}
              disabled={isSubmitting || !datasetName.trim() || !description.trim()}
              className="bg-[#FF7F7F] hover:bg-[#FF6666] text-white"
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Uploading...
                </>
              ) : (
                'Upload Dataset'
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
